PKG_NAME := scala-dep
URL := http://repo1.maven.org/maven2/biz/aQute/bnd/1.50.0/bnd-1.50.0.jar
ARCHIVES := http://repo1.maven.org/maven2/biz/aQute/bnd/1.50.0/bnd-1.50.0.pom . \
    http://repo1.maven.org/maven2/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.jar . \
    http://repo1.maven.org/maven2/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.pom . \
    http://repo1.maven.org/maven2/biz/aQute/bnd/parent/2.1.0/parent-2.1.0.pom . \
    http://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar . \
    http://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.pom . \
    http://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar . \
    http://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.pom . \
    http://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.1.2/logback-parent-1.1.2.pom . \
    http://repo1.maven.org/maven2/com/googlecode/jarjar/jarjar/1.3/jarjar-1.3.jar . \
    http://repo1.maven.org/maven2/com/googlecode/jarjar/jarjar/1.3/jarjar-1.3.pom . \
    http://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar . \
    http://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.pom . \
    http://repo1.maven.org/maven2/jline/jline/2.12.1/jline-2.12.1.jar . \
    http://repo1.maven.org/maven2/jline/jline/2.12.1/jline-2.12.1.pom . \
    http://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.jar . \
    http://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.pom . \
    http://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom . \
    http://repo1.maven.org/maven2/org/apache/felix/felix-parent/2.1/felix-parent-2.1.pom . \
    http://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.framework/4.4.0/org.apache.felix.framework-4.4.0.jar . \
    http://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.framework/4.4.0/org.apache.felix.framework-4.4.0.pom . \
    http://repo1.maven.org/maven2/org/eclipse/osgi/org.eclipse.osgi/3.7.1/org.eclipse.osgi-3.7.1.jar . \
    http://repo1.maven.org/maven2/org/eclipse/osgi/org.eclipse.osgi/3.7.1/org.eclipse.osgi-3.7.1.pom . \
    http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar . \
    http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom . \
    http://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/1.4.0/base-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/1.5.0/base-1.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-io/1.4.0/ops4j-base-io-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-io/1.4.0/ops4j-base-io-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-lang/1.4.0/ops4j-base-lang-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-lang/1.4.0/ops4j-base-lang-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-lang/1.5.0/ops4j-base-lang-1.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-monitors/1.4.0/ops4j-base-monitors-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-monitors/1.4.0/ops4j-base-monitors-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-net/1.4.0/ops4j-base-net-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-net/1.4.0/ops4j-base-net-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-spi/1.4.0/ops4j-base-spi-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-spi/1.4.0/ops4j-base-spi-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-store/1.4.0/ops4j-base-store-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-store/1.4.0/ops4j-base-store-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-util-property/1.4.0/ops4j-base-util-property-1.4.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/base/ops4j-base-util-property/1.4.0/ops4j-base-util-property-1.4.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/master/3.1.0/master-3.1.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/master/3.2.0/master-3.2.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/master/3.2.1/master-3.2.1.pom . \
    http://repo1.maven.org/maven2/org/ops4j/master/3.3.0/master-3.3.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam-reactor/3.5.0/exam-reactor-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/3.5.0/exam-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-container-native/3.5.0/pax-exam-container-native-3.5.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-container-native/3.5.0/pax-exam-container-native-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-junit4/3.5.0/pax-exam-junit4-3.5.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-junit4/3.5.0/pax-exam-junit4-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-link-assembly/3.5.0/pax-exam-link-assembly-3.5.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-link-assembly/3.5.0/pax-exam-link-assembly-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-spi/3.5.0/pax-exam-spi-3.5.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam-spi/3.5.0/pax-exam-spi-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam/3.5.0/pax-exam-3.5.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/exam/pax-exam/3.5.0/pax-exam-3.5.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/1.7.0/swissbox-1.7.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/1.8.0/swissbox-1.8.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-core/1.7.0/pax-swissbox-core-1.7.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-core/1.7.0/pax-swissbox-core-1.7.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-lifecycle/1.7.0/pax-swissbox-lifecycle-1.7.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-lifecycle/1.8.0/pax-swissbox-lifecycle-1.8.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-lifecycle/1.8.0/pax-swissbox-lifecycle-1.8.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-optional-jcl/1.7.0/pax-swissbox-optional-jcl-1.7.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-optional-jcl/1.7.0/pax-swissbox-optional-jcl-1.7.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-property/1.7.0/pax-swissbox-property-1.7.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-property/1.7.0/pax-swissbox-property-1.7.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-tracker/1.7.0/pax-swissbox-tracker-1.7.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-tracker/1.8.0/pax-swissbox-tracker-1.8.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/swissbox/pax-swissbox-tracker/1.8.0/pax-swissbox-tracker-1.8.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/tinybundles/tinybundles/2.0.0/tinybundles-2.0.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/tinybundles/tinybundles/2.0.0/tinybundles-2.0.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/2.0.0/url-2.0.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/2.2.0/url-2.2.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-aether/2.2.0/pax-url-aether-2.2.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-aether/2.2.0/pax-url-aether-2.2.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-classpath/2.0.0/pax-url-classpath-2.0.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-classpath/2.0.0/pax-url-classpath-2.0.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-commons/2.0.0/pax-url-commons-2.0.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-commons/2.0.0/pax-url-commons-2.0.0.pom . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-link/2.0.0/pax-url-link-2.0.0.jar . \
    http://repo1.maven.org/maven2/org/ops4j/pax/url/pax-url-link/2.0.0/pax-url-link-2.0.0.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/5.0.4-scala-3/scala-asm-5.0.4-scala-3.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/5.0.4-scala-3/scala-asm-5.0.4-scala-3.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-partest_2.11/1.0.13/scala-partest_2.11-1.0.13.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-partest_2.11/1.0.13/scala-partest_2.11-1.0.13.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.2/scala-swing_2.11-1.0.2-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.2/scala-swing_2.11-1.0.2-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.2/scala-swing_2.11-1.0.2.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.2/scala-swing_2.11-1.0.2.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.7/1.0.2/scala-continuations-plugin_2.11.7-1.0.2-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.7/1.0.2/scala-continuations-plugin_2.11.7-1.0.2-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.7/1.0.2/scala-continuations-plugin_2.11.7-1.0.2.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.7/1.0.2/scala-continuations-plugin_2.11.7-1.0.2.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.7/scala-compiler-2.11.7-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.7/scala-compiler-2.11.7-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.7/scala-compiler-2.11.7.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.7/scala-compiler-2.11.7.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.0/scala-library-2.11.0.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.4/scala-library-2.11.4-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.4/scala-library-2.11.4-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.4/scala-library-2.11.4.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.4/scala-library-2.11.4.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.pom . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.7/scala-reflect-2.11.7-javadoc.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.7/scala-reflect-2.11.7-sources.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.7/scala-reflect-2.11.7.jar . \
    http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.7/scala-reflect-2.11.7.pom . \
    http://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar . \
    http://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom . \
    http://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.11/1.11.6/scalacheck_2.11-1.11.6.jar . \
    http://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.11/1.11.6/scalacheck_2.11-1.11.6.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.5.11/slf4j-api-1.5.11.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.jar . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.5.11/slf4j-parent-1.5.11.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.6.6/slf4j-parent-1.6.6.pom . \
    http://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom . \
    http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom . \
    http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom . \

include ../common/Makefile.common
